server:
  use-forward-headers: true

keycloak:
  realm: dukecon-developer
  auth-server-url: https://keycloak.dukecon.org/auth
  ssl-required: none
  resource: dukecon
  credentials:
    secret: b2e0a96a-705a-48c2-8d04-b5d7c0c79bf7

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
# H2
  h2:
    console:
      enabled: true
      path: /h2
# Datasource
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration/common,classpath:db/migration/h2

---

keycloak:
  realm: dukecon-latest
  credentials:
    secret: 7585621d-bc63-4718-8d18-fc9cd2c6a22d

spring:
  profiles: latest

---

spring:
  profiles: debug-spring

logging:
  level:
    org:
      springframework: debug
      flywaydb: debug
